apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: websites

namespace: websites

resources:
  - ./10-rbac.yaml
  - ./20-service.yaml
  - ./30-deployment.yaml
  - ./40-ingress.yaml
